on: [push, workflow_dispatch]
name: build
jobs:
  build:
    name: Tacview Filter
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: haskell-actions/setup@v2
        id: build
        with:
          enable-stack: true
          stack-version: "latest"
          stack-no-global: true
      - run: stack --local-bin-path _build build --copy-bins

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Executables
          path: _build/

      - name: Release (if a new version is tagged)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            _build/tacview-filter.exe
            _build/tacview-replay.exe
            _build/tacview-server.exe
            _build/tacview-stats.exe
